version: '3.1'

services:
  app:
    image: app
    container_name: app
    ports:
      - 5000:5000
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: results
    ports:
      - 3306:3306
    volumes:
      - ./miniproject_db:/var/lib/mysql


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

