version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=u
            - RABBITMQ_DEFAULT_PASS=p
        ports:
            - "5672:5672"
    
    worker:
        build:        
            context: celery
            dockerfile: Dockerfile
    app:
        build:
            context: application
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        networks:
            - broker
            - database
        depends_on:
            - db
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_USER: root
            MYSQL_DATABASE: results
        ports:
            - 3306:3306
        volumes:
            - ./miniproject_db:/var/lib/mysql
        networks:
            - database
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - database
networks:
    broker:
    database:
